document.writeln("<!-- 脚注开始 -->");
document.writeln("	<div id=\'footer\'>");
document.writeln("		<div id=\'neir\' class=\'clearfix\'>");
document.writeln("			<div id=\'lxi\'>");
document.writeln("				<a href=\'#\'>联系我们</a> | <a href=\'#\'>法律声明</a> | <a href=\'#\'>下载中心</a> | <a href=\'#\'>邮箱登入</a>");
document.writeln("			</div>");
document.writeln("			<div id=\'copy\'>");
document.writeln("				<p>北京东方美景展览有限公司技术支持&nbsp;&nbsp;&nbsp;&nbsp;博鳌亚洲论坛版权所有&nbsp;&nbsp;&nbsp;&nbsp;琼ICP备案17004813号</p>");
document.writeln("				<p>Copyright &copy;2001-2019 BFA All Rights Reserved&nbsp;&nbsp;&nbsp;&nbsp;京公网备案 11010502034126号</p>");
document.writeln("			</div>");
document.writeln("			<div id=\'erwm\'>");
document.writeln("				<ul>");
document.writeln("					<li>");
document.writeln("						<img src=\'images/footer01.jpg\' alt=\'二维码\' >");
document.writeln("						<span>博鳌亚洲论坛</span>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<img src=\'images/footer01.jpg\' alt=\'二维码\' >");
document.writeln("						<span>论坛新浪微博</span>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<!-- 脚注结束 -->");