document.writeln("<div id=\'mask\'>");
document.writeln("		<div id=\'login\'>");
document.writeln("			<span id=\'close\' onclick=\'close_login()\'>X</span>");
document.writeln("			<div id=\'log_title\'>");
document.writeln("				<span>欢迎登入博鳌亚洲论坛</span>");
document.writeln("			</div>");
document.writeln("			<label for=\'account\'><input type=\'text\' name=\'account\' id=\'account\' placeholder=\'支持邮箱/手机号登入\' /></label>");
document.writeln("			<label for=\'password\'><input type=\'password\' name=\'password\' id=\'password\' placeholder=\'密码\' /></label>");
document.writeln("			<label for=\'into\'><input type=\'submit\' id=\'submit\' /></label>");
document.writeln("			<div id=\'oot\'>");
document.writeln("				<a href=\'#\'>忘记密码</a>");
document.writeln("				<a href=\'sign.html\' target=\'_blank\'>注册帐号</a>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<!-- 头部开始 -->");
document.writeln("		<div id=\'head\' class=\'clearfix\'>");
document.writeln("			<!-- logo -->");
document.writeln("			<div id=\'logo\'>");
document.writeln("				<img src=\'images/logo_m.png\' >");
document.writeln("			</div>");
document.writeln("			<!-- 登入、注册和搜索 -->");
document.writeln("			<div id=\'log_sign\'>");
document.writeln("				<span id=\'log_sp\' onclick=\'open_login()\'>登入</span><span>/</span><a href=\'sign.html\' target=\'_blank\'>注册</a>");
document.writeln("				<label for=\'sousuo\'>");
document.writeln("					<input type=\'text\' name=\'sousuo\' id=\'sousuo\' placeholder=\'请输入搜索关键字\' /><a href=\'#\'><img src=\'images/icons1.png\' alt=\'搜索图片\' /></a>");
document.writeln("				</label>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		<!-- 头部结束 -->");
document.writeln("		<!-- 导航栏开始 -->");
document.writeln("		<div id=\'menu\' class=\'clearfix\'>");
document.writeln("			<div id=\'link\'>");
document.writeln("				<ul>");
document.writeln("					<li><a href=\'index.html\'>首页</a><span></span></li>	");
document.writeln("					<li>");
document.writeln("						<a href=\'#\'>关于论坛</a><span></span>");
document.writeln("						<dl>");
document.writeln("							<a href=\'#\'><dd>背景介绍</dd></a>");
document.writeln("							<a href=\'#\'><dd>论坛章程</dd></a>");
document.writeln("							<a href=\'#\'><dd>理事会</dd></a>");
document.writeln("							<a href=\'#\'><dd>论坛资委会</dd></a>");
document.writeln("							<a href=\'#\'><dd>发起国+</dd></a>");
document.writeln("							<a href=\'#\'><dd>大事记</dd></a>");
document.writeln("							<a href=\'#\'><dd>海南博鳌</dd></a>");
document.writeln("							<a href=\'#\'><dd>联系我们</dd></a>");
document.writeln("						</dl>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'#\'>会议活动</a><span></span>");
document.writeln("						<dl>");
document.writeln("							<a href=\'#\'><dd>热点活动</dd></a>");
document.writeln("							<a href=\'#\'><dd>论坛年会</dd></a>");
document.writeln("							<a href=\'#\'><dd>其他活动</dd></a>");
document.writeln("						</dl>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'#\'>新闻中心</a><span></span>");
document.writeln("						<dl>");
document.writeln("							<a href=\'news_list.html\'><dd>新闻动态</dd></a>");
document.writeln("							<a href=\'#\'><dd>会议动态</dd></a>");
document.writeln("							<a href=\'#\'><dd>重要见会</dd></a>");
document.writeln("							<a href=\'#\'><dd>媒体报道</dd></a>");
document.writeln("							<a href=\'#\'><dd>图片资料</dd></a>");
document.writeln("							<a href=\'#\'><dd>视频资料</dd></a>");
document.writeln("							<a href=\'#\'><dd>下载中心</dd></a>");
document.writeln("							<a href=\'#\'><dd>媒体合作伙伴</dd></a>");
document.writeln("							<a href=\'#\'><dd>博鳌观点</dd></a>");
document.writeln("						</dl>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'#\'>会员与合作伙伴</a><span></span>");
document.writeln("						<dl style=\'width: 270px; left: -70px;\'>");
document.writeln("							<div class=\'member\'>");
document.writeln("								<dt>会员</dt>");
document.writeln("								<a href=\'#\'><dd>会员情况</dd></a>");
document.writeln("								<a href=\'#\'><dd>会员活动</dd></a>");
document.writeln("								<a href=\'#\'><dd>会员动态</dd></a>");
document.writeln("								<a href=\'#\'><dd>会员申请</dd></a>");
document.writeln("							</div>");
document.writeln("							<div class=\'partner\'>");
document.writeln("								<dt>合作伙伴</dt>");
document.writeln("								<a href=\'#\'><dd>合作伙伴鸣谢</dd></a>");
document.writeln("								<a href=\'#\'><dd>合作伙伴介绍</dd></a>");
document.writeln("								<a href=\'#\'><dd>合作伙伴动态</dd></a>");
document.writeln("								<a href=\'#\'><dd>合作伙伴申请</dd></a>");
document.writeln("							</div>");
document.writeln("						</dl>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'#\'>研究院</a><span></span>");
document.writeln("						<dl>");
document.writeln("							<a href=\'#\'><dd>研究院简介</dd></a>");
document.writeln("							<a href=\'#\'><dd>研究院动向</dd></a>");
document.writeln("							<a href=\'#\'><dd>研究院观点</dd></a>");
document.writeln("							<a href=\'#\'><dd>报告|课题</dd></a>");
document.writeln("							<a href=\'#\'><dd>刊物</dd></a>");
document.writeln("							<a href=\'#\'><dd>年会简报</dd></a>");
document.writeln("						</dl>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'#\'>关注领域</a><span></span>");
document.writeln("						<dl>");
document.writeln("							<a href=\'#\'><dd>金融|贸易|可持续发展</dd></a>");
document.writeln("							<a href=\'#\'><dd>健康|教育|科技</dd></a>");
document.writeln("							<a href=\'#\'><dd>媒体|文化</dd></a>");
document.writeln("							<a href=\'#\'><dd>经济合作及其他</dd></a>");
document.writeln("						</dl>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'#\'>区域事务</a><span></span>");
document.writeln("						<dl>");
document.writeln("							<a href=\'#\'><dd>亚太</dd></a>");
document.writeln("							<a href=\'#\'><dd>亚非</dd></a>");
document.writeln("							<a href=\'#\'><dd>欧洲</dd></a>");
document.writeln("							<a href=\'#\'><dd>其他</dd></a>");
document.writeln("						</dl>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		<!-- 导航栏结束 -->");