document.writeln("<div id=\'list_main\' class=\'clearfix\'>");
document.writeln("		<!-- left -->");
document.writeln("		<div id=\'list_main_left\'>");
document.writeln("			<div id=\'list_main_left_top\'>");
document.writeln("				<ul>");
document.writeln("					<li id=\'list_left_lit\'>新闻中心</li>");
document.writeln("					<a href=\'news_list.html\'><li class=\'list_left_li\'>新闻动态</li></a>");
document.writeln("					<a href=\'#\'><li class=\'list_left_li\'>博鳌观点</li></a>");
document.writeln("					<a href=\'#\'><li class=\'list_left_li\'>下载中心</li></a>");
document.writeln("					<a href=\'#\'><li class=\'list_left_li\'>媒体报道</li></a>");
document.writeln("					<a href=\'#\'><li class=\'list_left_li\'>重要会见</li></a>");
document.writeln("					<a href=\'#\'><li class=\'list_left_li\'>图片资料</li></a>");
document.writeln("					<a href=\'#\'><li class=\'list_left_li\'>视频资料</li></a>");
document.writeln("					<a href=\'#\'><li class=\'list_left_li\'>媒体合作</li></a>");
document.writeln("				</ul>");
document.writeln("			</div>");
document.writeln("			<div id=\'list_main_left_down\'>");
document.writeln("				<div id=\'list_meeting\'>");
document.writeln("					<a href=\'#\'>重要会见</a>");
document.writeln("				</div>");
document.writeln("				<div id=\'list_meeting_pic\'>");
document.writeln("					<ul>");
document.writeln("						<li>");
document.writeln("							<img src=\'images/important_03.png\' >");
document.writeln("							<div class=\'meet_pic\'>");
document.writeln("								李保东秘书长会见世界知识产权组织中国办事处主任刘华");
document.writeln("							</div>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<img src=\'images/important_01.png\' >");
document.writeln("							<div class=\'meet_pic\'>");
document.writeln("								李保东秘书长会见汶川县委书记张通荣");
document.writeln("							</div>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<img src=\'images/important_02.png\' >");
document.writeln("							<div class=\'meet_pic\'>");
document.writeln("								博鳌亚洲论坛秘书长李保东会见波兰驻华大使赛熙军");
document.writeln("							</div>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		<!-- right -->");
document.writeln("		<div id=\'list_main_right\'>");
document.writeln("			<div id=\'list_right_top\' class=\'clearfix\'>");
document.writeln("				<ul>");
document.writeln("					<li>你的当前位置</li>");
document.writeln("					<li>/</li>");
document.writeln("					<li>新闻中心</li>");
document.writeln("					<li>/</li>");
document.writeln("					<li>新闻动态</li>");
document.writeln("				</ul>");
document.writeln("			</div>");